'use strict';
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const base=__dirname,html=fs.readFileSync(base+'/panel.html','utf8');
const ctx=vm.createContext({});vm.runInContext(html.match(/<script>([\s\S]*?)<\/script>/)[1],ctx);
class Target { constructor(){this.events=new Map();this.style={};this.textContent='';this.disabled=false;} addEventListener(t,f){if(!this.events.has(t))this.events.set(t,new Set());this.events.get(t).add(f);} removeEventListener(t,f){this.events.get(t)?.delete(f);} emit(t){for(const f of [...(this.events.get(t)||[])])f({type:t});} setAttribute(){} count(){return [...this.events.values()].reduce((a,s)=>a+s.size,0);} }
function fixture(width){const els=new Map();const doc=new Target(),media=new Target(),win=new Target(),borrowed=()=>{};media.matches=false;media.addEventListener('change',borrowed);win.addEventListener('pagehide',borrowed);doc.hidden=false;doc.getElementById=id=>{if(!els.has(id))els.set(id,new Target());return els.get(id);};Object.assign(win,{innerWidth:width,innerHeight:900,devicePixelRatio:1,navigator:{userAgent:'Node VM fake DOM; no rendering, device or AT'},matchMedia:()=>media});let now=0,id=0;const queue=new Map();const env={document:doc,window:win,performance:{now:()=>now},requestAnimationFrame:f=>{queue.set(++id,f);return id;},cancelAnimationFrame:i=>queue.delete(i)};function step(dt=16.6667){now+=dt;const pending=[...queue.values()];queue.clear();pending.forEach(f=>f(now));}return {els,doc,media,win,env,queue,step,borrowed};}
const receipts=[];
for(const width of [1440,390]){const f=fixture(width);const baseline=f.win.count()+f.media.count()+f.doc.count();let callbacks=0;
 for(let cycle=0;cycle<10;cycle++){const panel=ctx.createPanel(f.env);assert.equal(f.queue.size,1);f.step();f.step();f.els.get('pause').emit('click');assert.equal(f.queue.size,0);const held=panel.report().state.elapsed;f.step(1000);assert.equal(panel.report().state.elapsed,held);f.els.get('pause').emit('click');assert.equal(f.queue.size,1);f.step();assert.equal(panel.report().state.elapsed,held);
 f.media.matches=true;f.media.emit('change');assert.equal(f.queue.size,0);assert.equal(panel.report().state.elapsed,6000);assert.equal(f.els.get('bar').style.transform,'scaleX(1)');assert.equal(f.els.get('badge').style.opacity,'1');assert.equal(f.els.get('marker').style.transform,'translateX(0px)');f.media.matches=false;f.media.emit('change');assert.equal(f.queue.size,0);panel.start();f.doc.hidden=true;f.doc.emit('visibilitychange');assert.equal(f.queue.size,0);f.doc.hidden=false;panel.start();for(let i=0;i<362;i++)f.step();assert.equal(panel.report().state.elapsed,6000);assert.equal(f.queue.size,0);panel.start();panel.dispose();panel.dispose();f.media.emit('change');f.win.emit('pagehide');assert.equal(f.queue.size,0);assert.equal(f.win.count()+f.media.count()+f.doc.count(),baseline);const r=panel.report();assert.equal(r.resources.ownedListeners,0);assert.equal(r.resources.ownedRaf,0);assert.equal(r.resources.borrowedMediaDisposed,false);receipts.push({width,cycle,owned:r.resources,observed:'pause/resume, finite complete, preference during execution, no automatic resume, hidden pause, restart, double dispose; borrowed listeners preserved'});callbacks+=r.summary.samples;
 } receipts.push({width,cycles:10,simulatedFrameSamples:callbacks});}
const result={caseId:'F005-N',probe:'Node VM fake DOM behavior; NOT browser/device/perception/performance/AT proof',assertions:'All assertions completed',checks:receipts,render:'UNVERIFIED',performance:'UNVERIFIED',assistiveTechnology:'UNVERIFIED'};
fs.writeFileSync(base+'/probe-receipt.json',JSON.stringify(result,null,2));console.log(JSON.stringify({caseId:result.caseId,assertions:result.assertions,cycles:20,render:result.render,performance:result.performance}));
