#!/usr/bin/env node
/* global document:readonly, innerWidth:readonly */
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const crypto=require('node:crypto');
const {chromium}=require('playwright');
const cycle=Number(process.argv.find(arg=>arg.startsWith('--cycle='))?.split('=')[1]||1);
assert(Number.isInteger(cycle)&&cycle>=1&&cycle<=3,'QA has at most three cycles');
const base=process.argv.find(arg=>arg.startsWith('--url='))?.slice(6)||'http://127.0.0.1:4179/transfer-navigation/';
const parsed=new URL(base);
assert(['127.0.0.1','localhost'].includes(parsed.hostname)&&parsed.protocol==='http:'&&parsed.pathname==='/transfer-navigation/','Only the authored loopback fixture may be tested');
const output=path.resolve(__dirname,'../output/navigation-20261002/author',`cycle-${cycle}`);
assert(!fs.existsSync(output),'Preserve previous evidence; choose the next bounded cycle');
fs.mkdirSync(output,{recursive:true});
const checks=[],failures=[],screenshots=[];
const started=Date.now();let browser,timeout;
const pass=(name,detail={})=>checks.push({name,status:'observed-pass',detail});
const sha=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
async function focus(page,selector){assert(await page.locator(selector).evaluate(node=>node===document.activeElement),`Expected focus on ${selector}`);}
async function capture(page,name){const file=path.join(output,`${name}.png`);await page.screenshot({path:file,fullPage:true});const dimensions=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,body:document.body.scrollWidth}));assert(dimensions.document<=dimensions.viewport&&dimensions.body<=dimensions.viewport,`Overflow ${name}`);screenshots.push({path:path.relative(path.resolve(__dirname,'../../..'),file).replace(/\\/g,'/'),sha256:sha(file)});pass(`overflow-${name}`,dimensions);}
async function fillRequest(page,title='Reparar o corrimão da torre C'){await page.locator('#title').fill(title);await page.locator('#location').fill('Torre C · escada do térreo');await page.locator('#description').fill('O corrimão apresenta uma fixação solta. Solicitar inspeção e reparo do suporte.');}
async function exercise(width){const context=await browser.newContext({viewport:{width,height:width===1440?1000:844},reducedMotion:'reduce'});const page=await context.newPage();page.on('pageerror',error=>failures.push({name:`pageerror-${width}`,reason:error.message}));await page.goto(base,{waitUntil:'networkidle'});assert.equal(await page.locator('#rows a').count(),6);await capture(page,`list-${width}`);
  await page.locator('#search').fill('elevador');await page.locator('#stage').selectOption('progress');assert.equal(await page.locator('#rows a').count(),1);assert.equal(await page.locator('[data-record-id="M-103"]').count(),1);const filteredURL=page.url();const recordLink=await page.locator('[data-record-id="M-103"]').getAttribute('href');assert.match(recordLink,/view=detail/);assert.match(recordLink,/q=elevador/);pass(`list-filters-real-link-${width}`,{filteredURL,recordLink});await page.locator('[data-record-id="M-103"]').focus();await page.keyboard.press('Enter');assert.match(page.url(),/id=M-103/);assert.equal(await page.locator('h1').textContent(),'M-103');await focus(page,'h1');assert.match(await page.locator('.record-title').textContent(),/Inspecionar/);assert(await page.locator('#panel-summary').isVisible());await capture(page,`detail-${width}`);
  await page.locator('#tab-summary').focus();await page.keyboard.press('ArrowRight');assert.equal(await page.locator('#tab-history').getAttribute('aria-selected'),'true');await focus(page,'#tab-history');assert(await page.locator('#panel-history').isVisible());assert.equal(await page.locator('#panel-summary').isVisible(),false);assert.match(page.url(),/tab=history/);assert.equal(await page.locator('.timeline li').count(),2);pass(`identity-tabs-keyboard-${width}`);await capture(page,`history-${width}`);await page.keyboard.press('Home');await focus(page,'#tab-summary');await page.locator('#back-list').click();assert.equal(await page.locator('#search').inputValue(),'elevador');assert.equal(await page.locator('#stage').inputValue(),'progress');assert.equal(await page.locator('#rows a').count(),1);await focus(page,'[data-record-id="M-103"]');pass(`return-retains-selection-and-focus-${width}`);await capture(page,`returned-${width}`);
  await page.locator('[data-record-id="M-103"]').click();await page.goBack();await page.locator('#search').waitFor();assert.equal(await page.locator('#search').inputValue(),'elevador');assert.equal(await page.locator('#stage').inputValue(),'progress');await focus(page,'[data-record-id="M-103"]');await page.goForward();await page.locator('#tab-summary').waitFor();assert.equal(await page.locator('h1').textContent(),'M-103');await focus(page,'h1');pass(`browser-back-forward-keeps-context-${width}`);
  await page.goto(`${base}?view=detail&id=M-101`,{waitUntil:'networkidle'});assert.equal(await page.locator('h1').textContent(),'M-101');assert.equal(await page.locator('#back-list').textContent(),'← Voltar à lista');await page.locator('#back-list').click();assert.equal(await page.locator('#rows a').count(),6);pass(`direct-entry-safe-return-${width}`);
  await page.goto(`${base}?view=detail&id=M-101&return=https%3A%2F%2Fevil.invalid%2Foutside&origin=external`,{waitUntil:'networkidle'});assert(await page.locator('#origin-notice').isVisible());const safe=await page.locator('#back-list').getAttribute('href');assert.equal(safe,'/transfer-navigation/?view=list');await page.locator('#back-list').click();assert(page.url().startsWith(base));pass(`untrusted-origin-is-not-redirect-${width}`,{safeReturn:safe});
  await page.goto(`${base}?view=detail&id=M-999`,{waitUntil:'networkidle'});assert.equal(await page.locator('[data-state="missing"]').count(),1);assert.equal(await page.locator('.description').count(),0);await capture(page,`not-found-${width}`);await page.locator('#back-list').click();await page.goto(`${base}?view=detail&id=M-106`,{waitUntil:'networkidle'});assert.equal(await page.locator('[data-state="denied"]').count(),1);assert.equal(await page.locator('.description').count(),0);await capture(page,`access-denied-${width}`);await page.locator('#back-list').click();await page.goto(`${base}?view=unknown`,{waitUntil:'networkidle'});assert.equal(await page.locator('[data-state="invalid"]').count(),1);await page.locator('#back-list').click();pass(`not-found-access-denied-invalid-distinct-${width}`);
  await page.locator('#search').fill('aucun résultat');assert.equal(await page.locator('#rows a').count(),0);assert(await page.locator('#empty-state').isVisible());await page.locator('#reset-list').click();assert.equal(await page.locator('#rows a').count(),6);await focus(page,'#search');pass(`empty-selection-recovery-${width}`);
  await page.locator('#create-link').click();await page.locator('#cancel-create').click();assert.equal(await page.locator('#rows a').count(),6);assert.equal(await page.locator('#created-success').count(),0);pass(`pristine-cancel-creates-nothing-${width}`);
  await page.locator('#search').fill('elevador');await page.locator('#stage').selectOption('progress');await page.locator('#create-link').click();await fillRequest(page);await page.locator('#cancel-create').click();assert(await page.locator('#abandon-dialog').evaluate(node=>node.open));await focus(page,'#keep-editing');await page.keyboard.press('Shift+Tab');await focus(page,'#discard-draft');await page.keyboard.press('Tab');await focus(page,'#keep-editing');await page.keyboard.press('Tab');await focus(page,'#discard-draft');await page.keyboard.press('Tab');await focus(page,'#keep-editing');pass(`dialog-real-keyboard-focus-contained-${width}`);await page.locator('#keep-editing').click();assert.equal(await page.locator('#title').inputValue(),'Reparar o corrimão da torre C');await focus(page,'#title');await page.locator('#cancel-create').click();await page.keyboard.press('Escape');assert.equal(await page.locator('#abandon-dialog').evaluate(node=>node.open),false);assert.equal(await page.locator('#title').inputValue(),'Reparar o corrimão da torre C');await page.locator('#cancel-create').click();await capture(page,`abandon-${width}`);await page.locator('#discard-draft').click();assert.equal(await page.locator('#search').inputValue(),'elevador');assert.equal(await page.locator('#stage').inputValue(),'progress');assert.equal(await page.locator('#rows a').count(),1);assert.equal(await page.locator('#created-success').count(),0);pass(`edited-cancel-confirmation-retains-list-${width}`);
  await page.goto(base,{waitUntil:'networkidle'});await page.locator('#create-link').click();await page.locator('#save-request').click();assert.equal(await page.locator('#title').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#location').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#description').getAttribute('aria-invalid'),'true');await focus(page,'#title');await capture(page,`validation-${width}`);pass(`validation-prevents-false-success-${width}`);
  await fillRequest(page);for(const id of ['title','location','description']){assert.equal(await page.locator(`#${id}`).getAttribute('aria-invalid'),'false');assert.equal(await page.locator(`#${id}-error`).isVisible(),false);}pass(`corrected-fields-clear-stale-errors-${width}`);await page.locator('.testing summary').click();await page.locator('#fail-next').check();await page.locator('#save-request').click();assert(await page.locator('#submit-error').isVisible());assert.match(page.url(),/view=create/);assert.equal(await page.locator('#title').inputValue(),'Reparar o corrimão da torre C');assert.equal(await page.locator('#location').inputValue(),'Torre C · escada do térreo');assert.equal(await page.locator('#created-success').count(),0);assert.equal(await page.locator('#fail-next').isChecked(),false);await capture(page,`submission-error-${width}`);pass(`explicit-error-preserves-draft-${width}`);
  await page.locator('#save-request').click();assert.match(page.url(),/view=detail&id=M-107/);assert.equal(await page.locator('h1').textContent(),'M-107');assert.match(await page.locator('.record-title').textContent(),/corrimão/);assert(await page.locator('#created-success').isVisible());await capture(page,`created-detail-${width}`);await page.locator('#back-list').click();assert.equal(await page.locator('#rows a').count(),7);assert.equal(await page.locator('[data-record-id="M-107"]').count(),1);await focus(page,'[data-record-id="M-107"]');pass(`retry-success-has-record-and-list-readback-${width}`);await capture(page,`created-list-${width}`);await page.locator('[data-record-id="M-107"]').click();await page.reload({waitUntil:'networkidle'});assert.equal(await page.locator('[data-state="missing"]').count(),1);await page.locator('#back-list').click();assert.equal(await page.locator('#rows a').count(),6);pass(`memory-persistence-limit-observed-${width}`);await context.close();}
(async()=>{try{timeout=setTimeout(()=>{failures.push({name:'timeout',reason:'QA exceeded the bounded 120 seconds'});browser?.close().catch(()=>{});},120000);browser=await chromium.launch({headless:true});for(const width of [1440,390,320]){try{await exercise(width);}catch(error){failures.push({name:`functional-${width}`,reason:error.message});break;}}}catch(error){failures.push({name:'execution',reason:error.message});}finally{clearTimeout(timeout);if(browser)await browser.close();const receipt={schemaVersion:1,kind:'authored-local-navigation-verification',fixture:'transfer-navigation',cycle,url:base,createdAt:new Date().toISOString(),durationMs:Date.now()-started,sourceHashes:{'index.html':sha(path.join(__dirname,'index.html')),'verify.cjs':sha(__filename)},checks,failures,screenshots,limitations:['Fictional local records and memory-only persistence','Access denial is an authored UI simulation, not authentication or authorization evidence','No backend, production, physical mobile, field accessibility or performance certification','No copied Mobbin media','No causal benchmark or expertise promotion']};const file=path.join(output,'receipt.json');fs.writeFileSync(file,JSON.stringify(receipt,null,2)+'\n');process.stdout.write(JSON.stringify({status:failures.length?'failed':'passed',checks:checks.length,failures,receipt:file})+'\n');if(failures.length)process.exitCode=1;}})();
