/**
 * Framework Config Check
 *
 * Verifies that SINAPSE framework configuration files are present.
 *
 * @module sinapse-ai/health-check/checks/project/framework-config
 * @version 1.0.0
 * @story HCS-2 - Health Check System Implementation
 */

const fs = require('fs').promises;
const path = require('path');
const { BaseCheck, CheckSeverity, CheckDomain } = require('../../base-check');

/**
 * Required framework config files
 */
const REQUIRED_CONFIGS = [
  { path: '.sinapse-ai', type: 'directory', description: 'SINAPSE core framework' },
  { path: '.claude', type: 'directory', description: 'Claude Code configuration' },
];

/**
 * Optional but recommended config files
 */
const RECOMMENDED_CONFIGS = [
  { path: '.sinapse', type: 'directory', description: 'SINAPSE local configuration' },
  { path: '.claude/CLAUDE.md', type: 'file', description: 'Project instructions' },
  { path: 'docs/framework', type: 'directory', description: 'Framework documentation' },
];

/**
 * Framework configuration check
 *
 * @class FrameworkConfigCheck
 * @extends BaseCheck
 */
class FrameworkConfigCheck extends BaseCheck {
  constructor() {
    super({
      id: 'project.framework-config',
      name: 'Framework Configuration',
      description: 'Verifies SINAPSE framework configuration is present',
      domain: CheckDomain.PROJECT,
      severity: CheckSeverity.HIGH,
      timeout: 3000,
      cacheable: true,
      healingTier: 1, // Can auto-create .sinapse local config dir
      tags: ['sinapse', 'config', 'framework'],
    });
  }

  /**
   * Execute the check
   * @param {Object} context - Execution context
   * @returns {Promise<Object>} Check result
   */
  async execute(context) {
    const projectRoot = context.projectRoot || process.cwd();
    const missingRequired = [];
    const missingRecommended = [];
    const found = [];

    // Check required configs
    for (const config of REQUIRED_CONFIGS) {
      const fullPath = path.join(projectRoot, config.path);
      try {
        const stats = await fs.stat(fullPath);
        const typeMatch = config.type === 'directory' ? stats.isDirectory() : stats.isFile();
        if (typeMatch) {
          found.push(config);
        } else {
          missingRequired.push(config);
        }
      } catch {
        missingRequired.push(config);
      }
    }

    // Check recommended configs
    for (const config of RECOMMENDED_CONFIGS) {
      const fullPath = path.join(projectRoot, config.path);
      try {
        const stats = await fs.stat(fullPath);
        const typeMatch = config.type === 'directory' ? stats.isDirectory() : stats.isFile();
        if (typeMatch) {
          found.push(config);
        } else {
          missingRecommended.push(config);
        }
      } catch {
        missingRecommended.push(config);
      }
    }

    // Report results
    if (missingRequired.length > 0) {
      const missing = missingRequired.map((c) => c.path).join(', ');
      return this.fail(`Missing required framework configuration: ${missing}`, {
        recommendation: 'Run SINAPSE setup or manually create missing directories',
        details: {
          missingRequired: missingRequired.map((c) => ({
            path: c.path,
            description: c.description,
          })),
          found: found.map((c) => c.path),
        },
      });
    }

    if (missingRecommended.length > 0) {
      const missing = missingRecommended.map((c) => c.path).join(', ');
      return this.warning(`Missing recommended configuration: ${missing}`, {
        recommendation: 'Run health check with --fix to create missing recommended configuration',
        healable: true,
        healingTier: 1,
        details: {
          missingRecommended: missingRecommended.map((c) => ({
            path: c.path,
            description: c.description,
          })),
          found: found.map((c) => c.path),
        },
      });
    }

    return this.pass('All framework configuration present', {
      details: { found: found.map((c) => c.path) },
    });
  }

  /**
   * Get healer for this check
   * @returns {Object} Healer configuration
   */
  getHealer() {
    return {
      name: 'create-sinapse-local-config',
      action: 'create-config',
      successMessage: 'Created .sinapse local configuration directory',
      fix: async (_result) => {
        const projectRoot = process.cwd();
        const sinapseDir = path.join(projectRoot, '.sinapse');

        await fs.mkdir(sinapseDir, { recursive: true });

        const configPath = path.join(sinapseDir, 'config.yaml');
        try {
          await fs.access(configPath);
        } catch {
          // Create minimal config stub if it doesn't exist
          const stub = [
            '# SINAPSE local configuration',
            '# Generated by SINAPSE Health Check auto-heal',
            'permissions:',
            '  mode: ask',
          ].join('\n') + '\n';
          await fs.writeFile(configPath, stub, 'utf8');
        }

        return { success: true, message: 'Created .sinapse/config.yaml' };
      },
    };
  }
}

module.exports = FrameworkConfigCheck;

